targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/api/api.dart
              schema: lib/schema.graphql
              queries_glob: lib/graphql/**.graphql