// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSUKNw2Ykh-hhjPy4MsFJMWVMd1ghuYGI',
    appId: '1:670924580558:web:78430f9283c9b5b275529f',
    messagingSenderId: '670924580558',
    projectId: 'secret-fire',
    authDomain: 'secret-fire.firebaseapp.com',
    storageBucket: 'secret-fire.appspot.com',
    measurementId: 'G-6H8ZSW5P86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5gqAnAW3hWTWd78X_PC2aFaufUBNACV4',
    appId: '1:670924580558:android:efb53ecc1d7a382b75529f',
    messagingSenderId: '670924580558',
    projectId: 'secret-fire',
    storageBucket: 'secret-fire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcK_1ftvbcCqrkga06jmKDXmAEeSRg-0M',
    appId: '1:670924580558:ios:46629a71eb3905bc75529f',
    messagingSenderId: '670924580558',
    projectId: 'secret-fire',
    storageBucket: 'secret-fire.appspot.com',
    iosClientId: '670924580558-photlnlnqdr1ll43h254jr6bmi8bptmc.apps.googleusercontent.com',
    iosBundleId: 'com.example.secretFe',
  );
}
