name: Build

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v1
      with:
          channel: 'stable'
    - run: flutter pub get
    - run: flutter clean
    - run: flutter build web

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/web